const config = require("../config");
const strings = require("./languages")

const CONSTANTS = Object.freeze({
  MAP_RADIUS: 5,
  NB_PAWNS: config.TEST ? 2 : 4,
  // NB_PAWNS: 4,
  MAX_HP_PLAYER: config.TEST ? 1 : 4,
  // MAX_HP_PLAYER: 4,
  TEAM_RED: "red",
  TEAM_BLUE: "cyan",
  PICK_BAN_ORDER: ["PICK", "PICK", "PICK", "PICK"],
  // PICK_BAN_ORDER: ["BAN", "BAN", "PICK", "PICK", "PICK", "PICK"],
  TIME_TURN_MS: 60000,
});
const GAME_MODE = Object.freeze({
  QUICK: "QUICK",
  DRAFT: "DRAFT",
});

const CANVAS = Object.freeze({
  WIDTH: 1600,
  HEIGHT: 900,
});

const ANIMATIONS = {
  FALL: "FALL",
};

const TYPES = Object.freeze({
  //cell types
  ANY: "ANY",
  LAVA: "LAVA",
  EMPTY: "EMPTY",
  CLOSE_TO_LAVA: "CLOSE_TO_LAVA",
  //entities types
  ENTITY: "ENTITY",
  PLAYABLE: "PLAYABLE",
  PLAYER: "PLAYER",
  VULNERABLE: "VULNERABLE",
  // summons types
  LAUNCHED: "LAUNCHED", //generic for animation
  SHADOW: "SHADOW",
  BOMB: "BOMB",
  INFERNAL: "INFERNAL",
  BARREL: "BARREL",
});

const GAMEDATA = Object.freeze({
  //summons
  TABLE_SUMMONS: {
    shadow: {
      id: "shadow",
      name: strings.summons.shadow.name,
      ttl: -1,
      summonTypes: [TYPES.SHADOW, TYPES.LAUNCHED],
      isUnique: true,
    },
    wall: {
      id: "wall",
      name: strings.summons.wall.name,
      ttl: 1,
      summonTypes: [TYPES.LAUNCHED],
    },
    tentacle: {
      id: "tentacle",
      name: strings.summons.tentacle.name,
      ttl: 1,
      summonTypes: [],
      auras: [
        {
          name: strings.summons.tentacle.auras[0].name,
          dealSpell: "damage",
          aoe: "tentacle_hit",
          isAura: true,
          glyph: 1,
          color: "GLYPH_BROWN",
        },
      ],
    },
    infernal: {
      id: "infernal",
      name: strings.summons.infernal.name,
      ttl: -1,
      maxHP: 3,
      isUnique: true,
      summonTypes: [TYPES.INFERNAL, TYPES.PLAYABLE, TYPES.VULNERABLE],
      auras: [
        {
          name: strings.summons.infernal.auras[0].name,
          permanent: true,
          dealSpell: "damage",
          aoe: "ring_1",
          isAura: true,
          glyph: 1,
          color: "GLYPH_BROWN",
          glyphIcon: "damageIcon",
          src: "./pics/spells/infernal_aura.png",
        },
      ],
      spells: [
        {
          passive: true,
          cooldown: 0,
          name: strings.summons.infernal.spells[0].name,
          permanent: true,
          dealSpell: "damage",
          aoe: "ring_1",
          isAura: true,
          glyph: 1,
          color: "GLYPH_BROWN",
          glyphIcon: "damageIcon",
          src: "./pics/spells/infernal_aura.png",
          description: strings.summons.infernal.spells[0].description,
        },
      ],
    },
    barrel: {
      id: "barrel",
      name: strings.summons.barrel.name,
      ttl: -1,
      summonTypes: [TYPES.BARREL, TYPES.LAUNCHED, TYPES.VULNERABLE],
      maxHP: 1,
      onDeath: "rasta_barrel_explode",
      auras: [
        {
          name: strings.summons.barrel.auras[0].name,
          permanent: true,
          dealSpell: "nothing",
          aoe: "area_1",
          isAura: true,
          glyph: 1,
          color: "GLYPH_PREVIEW",
        },
      ],
    },
    time_machine: {
      id: "time_machine",
      name: strings.summons.time_machine.name,
      ttl: 1,
      summonTypes: [TYPES.LAUNCHED, TYPES.VULNERABLE],
      maxHP: 1,
      auras: [
        {
          name: strings.summons.time_machine.auras.time_machine.name,
          dealSpell: "blink",
          aoe: "single",
          isAura: true,
          glyph: 1,
          color: "GLYPH_PREVIEW",
        },
        {
          name: strings.summons.time_machine.auras.explosion.name,
          dealSpell: "damage",
          aoe: "ring_1",
          isAura: true,
          glyph: 1,
          color: "GLYPH_BROWN",
        },
      ],
    },

    zombie: {
      id: "zombie",
      name: strings.summons.zombie.name,
      ttl: -1,
      maxHP: 1,
      summonTypes: [TYPES.PLAYABLE, TYPES.VULNERABLE],
      auras: [],
      movePoint: 0,
      spells: [
        {
          name: strings.summons.zombie.spells.zombie_crawl.name,
          dealSpell: "zombie_crawl",
          range: 1,
          rangeMin: 1,
          cooldown: 1,
          aoe: "single",
          src: "./pics/spells/zombie_crawl.png",
          canTarget: [TYPES.ANY],
          description: strings.summons.zombie.spells.zombie_crawl.description,
        },
      ],
    },
  },

  LAVA_SPELL: {
    name: strings.general.LAVA_SPELL.name,
    dealSpell: "riseLava",
    range: 9,
    aoe: "single",
    canTarget: [TYPES.EMPTY],
    description:strings.general.LAVA_SPELL.description,
  },
  PASS_SPELL: {
    name: strings.general.PASS_SPELL.name,
    description: strings.general.PASS_SPELL.description,
  },
  MOVE_SPELL: {
    name: strings.general.MOVE_SPELL.name,
    description: strings.general.MOVE_SPELL.description,
  },
  
  CHARACTERS: [
    {
      id: "mage",
      name: strings.characters.mage.name,
      difficulty: 1, //1 to 3
      title: strings.characters.mage.title,
      description: strings.characters.mage.description,
      spells: [
        {
          id: "mage_0",
          name: strings.characters.mage.spells[0].name,
          dealSpell: "damage",
          range: 4,
          rangeMin: 2,
          cooldown: 1,
          aoe: "straight_line_inferno",
          glyph: 1,
          color: "GLYPH_BROWN",
          glyphIcon: "damageIcon",
          canTarget: [TYPES.ANY],
          description: strings.characters.mage.spells[0].description,
        },
        {
          id: "mage_1",
          name: strings.characters.mage.spells[1].name,
          dealSpell: "root",
          range: 2,
          rangeMin: 2,
          cooldown: 3,
          aoe: "square",
          canTarget: [TYPES.ANY],
          description: strings.characters.mage.spells[1].description,
        },
        {
          id: "mage_2",
          name: strings.characters.mage.spells[2].name,
          dealSpell: "mage_force",
          range: 0,
          cooldown: 2,
          aoe: "ring_1",
          canTarget: [TYPES.PLAYABLE],
          animation: ANIMATIONS.FALL,
          description: strings.characters.mage.spells[2].description,
        },
      ],
    },
    {
      id: "fisherman",
      name: strings.characters.fisherman.name,
      difficulty: 1,
      title: strings.characters.fisherman.title,
      description: strings.characters.fisherman.description,
      spells: [
        {
          id: "fisherman_0",
          name: strings.characters.fisherman.spells[0].name,
          dealSpell: "pull",
          range: 5,
          rangeMin: 1,
          cooldown: 2,
          aoe: "straight_line",
          onlyFirst: true,
          canTarget: [TYPES.ENTITY],
          description: strings.characters.fisherman.spells[0].description,
        },
        {
          id: "fisherman_1",
          name: strings.characters.fisherman.spells[1].name,
          dealSpell: "root",
          range: 4,
          cooldown: 2,
          aoe: "pair",
          glyph: 1,
          color: "GLYPH_BLUE",
          glyphIcon: "rootIcon",
          canTarget: [TYPES.ANY],
          description: strings.characters.fisherman.spells[1].description,
        },
        {
          id: "fisherman_2",
          name: strings.characters.fisherman.spells[2].name,
          dealSpell: "fisherman_push",
          range: 1,
          rangeMin: 1,
          cooldown: 1,
          aoe: "single",
          value: "1",
          canTarget: [TYPES.ENTITY],
          description: strings.characters.fisherman.spells[2].description,
        },
      ],
    },
    {
      id: "golem",
      name: strings.characters.golem.name,
      difficulty: 2,
      title: strings.characters.golem.title,
      description: strings.characters.golem.description,
      spells: [
        {
          id: "golem_0",
          name: strings.characters.golem.spells[0].name,
          dealSpell: "golem_boulder",
          range: 4,
          cooldown: 1,
          aoe: "single",
          glyph: 1,
          color: "GLYPH_ORANGE",
          onMiss: "lava",
          glyphIcon: "boulderIcon",
          canTarget: [TYPES.ANY],
          animation: ANIMATIONS.FALL,
          description: strings.characters.golem.spells[0].description,
        },
        {
          id: "golem_1",
          name: strings.characters.golem.spells[1].name,
          dealSpell: "summon",
          summon: "wall",
          range: 3,
          cooldown: 3,
          aoe: "curly",
          ttl: 1,
          canTarget: [TYPES.ANY],
          description: strings.characters.golem.spells[1].description,
        },
        {
          id: "golem_2",
          name: strings.characters.golem.spells[2].name,
          dealSpell: "damage",
          range: 0,
          cooldown: 2,
          aoe: "ring_1",
          isAura: true,
          glyph: 1,
          color: "GLYPH_BROWN",
          glyphIcon: "damageIcon",
          canTarget: [TYPES.PLAYABLE],
          description: strings.characters.golem.spells[2].description,
        },
      ],
    },
    {
      id: "ninja",
      name: strings.characters.ninja.name,
      difficulty: 2,
      title: strings.characters.ninja.title,
      description: strings.characters.ninja.description,
      spells: [
        {
          id: "ninja_0",
          name: strings.characters.ninja.spells[0].name,
          dealSpell: "summon",
          summon: "shadow",
          range: 2,
          rangeMin: 1,
          cooldown: 3,
          aoe: "single",
          canTarget: [TYPES.EMPTY],
          description: strings.characters.ninja.spells[0].description,
        },
        {
          id: "ninja_1",
          name: strings.characters.ninja.spells[1].name,
          dealSpell: "ninja_slash", //damage + anim
          range: 0,
          cooldown: 2,
          aoe: "ninja_slash",
          canTarget: [TYPES.PLAYABLE],
          description: strings.characters.ninja.spells[1].description,
        },
        {
          id: "ninja_2",
          name: strings.characters.ninja.spells[2].name,
          dealSpell: "switcheroo",
          range: 8,
          cooldown: 2,
          aoe: "single",
          canTarget: [TYPES.SHADOW],
          description: strings.characters.ninja.spells[2].description,
        },
      ],
    },
    {
      id: "demonist",
      name: strings.characters.demonist.name,
      difficulty: 2,
      title: strings.characters.demonist.title,
      description: strings.characters.demonist.description,
      spells: [
        {
          id: "demonist_0",
          name: strings.characters.demonist.spells[0].name,
          dealSpell: "demo_tentacle",
          summon: "tentacle",
          range: 3,
          rangeMin: 3,
          cooldown: 1,
          aoe: "tentacle",
          onlyFirst: true,
          canTarget: [TYPES.EMPTY],
          description: strings.characters.demonist.spells[0].description,
        },
        {
          id: "demonist_1",
          name: strings.characters.demonist.spells[1].name,
          dealSpell: "summon",
          summon: "infernal",
          range: 1,
          rangeMin: 1,
          cooldown: 5,
          aoe: "single",
          canTarget: [TYPES.EMPTY],
          description: strings.characters.demonist.spells[1].description,
        },
        {
          id: "demonist_2",
          name: strings.characters.demonist.spells[2].name,
          dealSpell: "buffPM",
          range: 1,
          cooldown: 3,
          aoe: "single",
          canTarget: [TYPES.PLAYABLE],
          description: strings.characters.demonist.spells[2].description,
        },
      ],
    },
    {
      id: "rasta",
      name: strings.characters.rasta.name,
      difficulty: 1,
      title: strings.characters.rasta.title,
      description: strings.characters.rasta.description,
      spells: [
        {
          id: "rasta_0",
          name: strings.characters.rasta.spells[0].name,
          dealSpell: "damage",
          range: 9,
          cooldown: 1,
          aoe: "line",
          aoeSize: 5,
          glyph: 1,
          canTarget: [TYPES.ANY],
          color: "GLYPH_BROWN",
          glyphIcon: "damageIcon",
          animation: ANIMATIONS.FALL,
          description: strings.characters.rasta.spells[0].description,
        },
        {
          id: "rasta_1",
          name: strings.characters.rasta.spells[1].name,
          dealSpell: "summon",
          summon: "barrel",
          range: 2,
          rangeMin: 1,
          cooldown: 2,
          aoe: "single",
          canTarget: [TYPES.EMPTY],
          description: strings.characters.rasta.spells[1].description,
        },
        {
          id: "rasta_2",
          name: strings.characters.rasta.spells[2].name,
          dealSpell: "buffPM",
          value: 2,
          range: 0,
          cooldown: 3,
          aoe: "single",
          canTarget: [TYPES.PLAYABLE],
          description: strings.characters.rasta.spells[2].description,
        },
      ],
    },
    {
      id: "assassin",
      name: strings.characters.assassin.name,
      difficulty: 1,
      title: strings.characters.assassin.title,
      description: strings.characters.assassin.description,
      spells: [
        {
          id: "assassin_0",
          name: strings.characters.assassin.spells[0].name,
          dealSpell: "damage",
          range: 1,
          rangeMin: 1,
          cooldown: 1,
          aoe: "single",
          canTarget: [TYPES.VULNERABLE],
          description: strings.characters.assassin.spells[0].description,
        },
        {
          id: "assassin_1",
          name: strings.characters.assassin.spells[1].name,
          dealSpell: "damage",
          range: 3,
          rangeMin: 3,
          cooldown: 3,
          aoe: "single_straight_line",
          canTarget: [TYPES.VULNERABLE],
          description: strings.characters.assassin.spells[1].description,
        },
        {
          id: "assassin_2",
          name: strings.characters.assassin.spells[2].name,
          dealSpell: "assassin_smokebomb",
          range: 1,
          rangeMin: 1,
          cooldown: 3,
          aoe: "ring_1_on_self",
          canTarget: [TYPES.EMPTY],
          description: strings.characters.assassin.spells[2].description,
        },
      ],
    },
    {
      id: "time_traveler",
      name: strings.characters.time_traveler.name,
      difficulty: 3,
      title: strings.characters.time_traveler.title,
      description: strings.characters.time_traveler.description,
      spells: [
        {
          id: "time_traveler_0",
          name: strings.characters.time_traveler.spells[0].name,
          dealSpell: "summon",
          summon: "time_machine",
          range: 3,
          rangeMin: 1,
          cooldown: 2,
          aoe: "single",
          glyph: 0,
          canTarget: [TYPES.EMPTY],
          description: strings.characters.time_traveler.spells[0].description,
        },
        {
          id: "time_traveler_1",
          name: strings.characters.time_traveler.spells[1].name,
          dealSpell: "time_backwards_hit",
          range: 1,
          rangeMin: 1,
          cooldown: 2,
          aoe: "single",
          canTarget: [TYPES.VULNERABLE],
          description: strings.characters.time_traveler.spells[1].description,
        },
        {
          id: "time_traveler_2",
          name: strings.characters.time_traveler.spells[2].name,
          dealSpell: "silence",
          range: 3,
          rangeMin: 0,
          cooldown: 2,
          aoe: "handspinner",
          glyph: 1,
          color: "GLYPH_PURPLE",
          glyphIcon: "silenceIcon",
          canTarget: [TYPES.ANY],
          description: strings.characters.time_traveler.spells[2].description,
        },
      ],
    },
    {
      id: "shaman",
      name: strings.characters.shaman.name,
      difficulty: 2,
      title: strings.characters.shaman.title,
      description: strings.characters.shaman.description,
      spells: [
        {
          id: "shaman_0",
          name: strings.characters.shaman.spells[0].name,
          dealSpell: "summon",
          summon: "zombie",
          range: 1,
          rangeMin: 1,
          cooldown: 1,
          glyph: 1,
          aoe: "single",
          canTarget: [TYPES.EMPTY],
          color: "GLYPH_DARK",
          glyphIcon: "tombstoneIcon",
          description: strings.characters.shaman.spells[0].description,
        },
        {
          id: "shaman_1",
          name: strings.characters.shaman.spells[1].name,
          dealSpell: "damage",
          range: 9,
          rangeMin: 4,
          cooldown: 1,
          aoe: "single",
          glyph: 1,
          color: "GLYPH_DARK",
          glyphIcon: "gasIcon",
          canTarget: [TYPES.ANY],
          permanent: true,
          description: strings.characters.shaman.spells[1].description,
        },
        {
          id: "shaman_2",
          name: strings.characters.shaman.spells[2].name,
          dealSpell: "silence",
          range: 2,
          rangeMin: 1,
          cooldown: 3,
          aoe: "single",
          canTarget: [TYPES.PLAYABLE],
          description: strings.characters.shaman.spells[2].description,
        },
      ],
    },
    {
      id: "random",
      name: strings.characters.random.name,
      difficulty: 5,
      title: strings.characters.random.title,
      description: strings.characters.random.description,
      spells: [
        {
          id: "random_0",
          name: strings.characters.random.spells[0].name,
          cooldown: strings.characters.random.spells[0].cooldown,
          description: strings.characters.random.spells[0].description,
        },
        {
          id: "random_1",
          name: strings.characters.random.spells[1].name,
          cooldown: strings.characters.random.spells[1].cooldown,
          description: strings.characters.random.spells[1].description,
        },
        {
          id: "random_2",
          name: strings.characters.random.spells[2].name,
          cooldown: strings.characters.random.spells[2].cooldown,
          description: strings.characters.random.spells[2].description,
        },
      ],
    },
    {
      id: "pangolino",
      name: strings.characters.pangolino.name,
      difficulty: 1,
      title: strings.characters.pangolino.title,
      description: strings.characters.pangolino.description,
      spells: [
        {
          id: "pangolino_0",
          name: strings.characters.pangolino.spells[0].name,
          dealSpell: "pango_spiky_ball",
          range: 0,
          cooldown: 2,
          aoe: "single",
          canTarget: [TYPES.PLAYABLE],
          description: strings.characters.pangolino.spells[0].description,
        },
        {
          id: "pangolino_1",
          name: strings.characters.pangolino.spells[1].name,
          dealSpell: "shield",
          range: 0,
          cooldown: 2,
          aoe: "single",
          canTarget: [TYPES.VULNERABLE],
          color: "GLYPH_GAZ",
          description: strings.characters.pangolino.spells[1].description,
        },
        {
          id: "pangolino_2",
          name: strings.characters.pangolino.spells[2].name,
          dealSpell: "root",
          range: 3,
          cooldown: 2,
          aoe: "single",
          permanent: true,
          onlyFirst: true,
          glyph: 1,
          color: "GLYPH_GAZ",
          glyphIcon: "rootIcon",
          canTarget: [TYPES.EMPTY],
          description: strings.characters.pangolino.spells[2].description,
        },
      ],
    },
    {
      id: "warrior",
      name: strings.characters.warrior.name,
      difficulty: 1,
      title: strings.characters.warrior.title,
      description: strings.characters.warrior.description,
      spells: [
        {
          id: "warrior_0",
          name: strings.characters.warrior.spells[0].name,
          dealSpell: "damage",
          range: 1,
          rangeMin: 1,
          cooldown: 1,
          aoe: "cleave",
          glyph: 1,
          isAura: true,
          color: "GLYPH_BROWN",
          glyphIcon: "damageIcon",
          canTarget: [TYPES.ANY],
          description: strings.characters.warrior.spells[0].description,
        },
        {
          id: "warrior_1",
          name: strings.characters.warrior.spells[1].name,
          dealSpell: "shield",
          range: 0,
          cooldown: 2,
          aoe: "area_1",
          canTarget: [TYPES.VULNERABLE],
          color: "GLYPH_ORANGE",
          description: strings.characters.warrior.spells[1].description,
        },
        {
          id: "warrior_2",
          name: strings.characters.warrior.spells[2].name,
          dealSpell: "warrior_charge",
          range: 4,
          rangeMin: 1,
          cooldown: 3,
          aoe: "straight_line",
          onlyFirst: true,
          canTarget: [TYPES.ENTITY],
          description: strings.characters.warrior.spells[2].description,
        },
      ],
    },
    {
      id: "gasser",
      name: strings.characters.gasser.name,
      difficulty: 2,
      title: strings.characters.gasser.title,
      description: strings.characters.gasser.description,
      spells: [
        {
          id: "gasser_0",
          name: strings.characters.gasser.spells[0].name,
          dealSpell: "damage_others",
          range: 0,
          cooldown: 0,
          aoe: "single",
          glyph: 1,
          color: "GLYPH_GAZ",
          passive: true,
          permanent: true,
          onMove: true,
          selfCast: true,
          glyphIcon: "gasIcon",
          canTarget: [TYPES.VULNERABLE],
          description: strings.characters.gasser.spells[0].description,
        },
        {
          id: "gasser_1",
          name: strings.characters.gasser.spells[1].name,
          dealSpell: "buffPM",
          range: 0,
          cooldown: 2,
          aoe: "single",
          value: 2,
          canTarget: [TYPES.ENTITY],
          description: strings.characters.gasser.spells[1].description,
        },
        {
          id: "gasser_2",
          name: strings.characters.gasser.spells[2].name,
          dealSpell: "gasser_shotgun",
          range: 1,
          rangeMin: 1,
          cooldown: 1,
          aoe: "single",
          canTarget: [TYPES.VULNERABLE],
          description: strings.characters.gasser.spells[2].description,
        },
      ],
    },
    {
      id: "lava_elemental",
      name: strings.characters.lava_elemental.name,
      difficulty: 3,
      title: strings.characters.lava_elemental.title,
      description: strings.characters.lava_elemental.description,
      spells: [
        {
          id: "lava_elemental_0",
          name: strings.characters.lava_elemental.spells[0].name,
          dealSpell: "damage",
          range: 1,
          cooldown: 1,
          aoe: "handspinner",
          glyph: 1,
          color: "GLYPH_BROWN",
          glyphIcon: "damageIcon",
          canTarget: [TYPES.ANY],
          specialRange: TYPES.CLOSE_TO_LAVA,
          animation: ANIMATIONS.FALL,
          description: strings.characters.lava_elemental.spells[0].description,
        },
        {
          id: "lava_elemental_1",
          name: strings.characters.lava_elemental.spells[1].name,
          dealSpell: "damage_others",
          range: -1,
          cooldown: 2,
          aoe: "lava_sulfur_fumes",
          glyph: 1,
          color: "GLYPH_ORANGE",
          glyphIcon: "damageIcon",
          canTarget: [TYPES.CLOSE_TO_LAVA],
          specialRange: TYPES.CLOSE_TO_LAVA,
          animation: ANIMATIONS.FALL,
          description: strings.characters.lava_elemental.spells[1].description,
        },
        {
          id: "lava_elemental_2",
          name: strings.characters.lava_elemental.spells[2].name,
          dealSpell: "lava_flow",
          range: -1,
          rangeMin: 1,
          cooldown: 3,
          aoe: "single",
          canTarget: [TYPES.CLOSE_TO_LAVA, TYPES.EMPTY],
          specialRange: TYPES.CLOSE_TO_LAVA,
          description: strings.characters.lava_elemental.spells[2].description,
        },
      ],
    },
    {
      id: "water_elemental",
      name: strings.characters.water_elemental.name,
      difficulty: 3,
      title: strings.characters.water_elemental.title,
      description: strings.characters.water_elemental.description,
      spells: [
        {
          id: "water_elemental_0",
          name: strings.characters.water_elemental.spells[0].name,
          dealSpell: "damage",
          range: 4,
          cooldown: 2,
          aoe: "ring_1",
          glyph: 1,
          color: "GLYPH_WATER",
          canTarget: [TYPES.ANY],
          description: strings.characters.water_elemental.spells[0].description,
        },
        {
          id: "water_elemental_1",
          name: strings.characters.water_elemental.spells[1].name,
          dealSpell: "water_splash",
          range: 3,
          rangeMin: 2,
          cooldown: 3,
          aoe: "pair",
          onlyFirst: true,
          canTarget: [TYPES.ENTITY],
          description: strings.characters.water_elemental.spells[1].description,
        },
        {
          id: "water_elemental_2",
          name: strings.characters.water_elemental.spells[2].name,
          dealSpell: "damage",
          isGoingForward: true,
          range: 1,
          rangeMin: 1,
          cooldown: 2,
          aoe: "cleave",
          glyph: 1,
          color: "GLYPH_WATER",
          glyphIcon: "waveIcon",
          canTarget: [TYPES.ANY],
          description: strings.characters.water_elemental.spells[2].description,
        },
      ],
    },
    {
      id: "ethereal",
      name: strings.characters.ethereal.name,
      difficulty: 3,
      title: strings.characters.ethereal.title,
      description: strings.characters.ethereal.description,
      spells: [
        {
          id: "ethereal_0",
          name: strings.characters.ethereal.spells[0].name,
          dealSpell: "ethereal_form",
          value: 1,
          range: 0,
          cooldown: 2,
          aoe: "single",
          canTarget: [TYPES.VULNERABLE],
          description: strings.characters.ethereal.spells[0].description,
        },
        {
          id: "ethereal_1",
          name: strings.characters.ethereal.spells[1].name,
          dealSpell: "damage",
          range: 1,
          rangeMin: 1,
          cooldown: 3,
          aoe: "single",
          canTarget: [TYPES.VULNERABLE],
          description: strings.characters.ethereal.spells[1].description,
        },
        {
          id: "ethereal_2",
          name: strings.characters.ethereal.spells[2].name,
          dealSpell: "damage",
          range: 4,
          rangeMin: 1,
          cooldown: 1,
          aoe: "handspinner",
          glyph: 1,
          color: "GLYPH_BLUE",
          glyphIcon: "damageIcon",
          canTarget: [TYPES.VULNERABLE],
          description: strings.characters.ethereal.spells[2].description,
        },
      ],
    },

  ],

});

module.exports = {
  CONSTANTS,
  CANVAS,
  TYPES,
  GAMEDATA,
  ANIMATIONS,
  GAME_MODE,
};
