name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Deployment Script
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        USER: ${{ secrets.USER }}
      run: |
        ssh $USER@$SERVER_IP -o StrictHostKeyChecking=no << EOF
        cd lava-chess
        sudo git pull origin main
        mv config-prod.sj config.js
        sudo browserify client.js -o public/main.js
        sudo pm2 restart 0
        EOF
