name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: 'unnecessary'

    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SERVER_IP }}  >> ~/.ssh/known_hosts

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Deployment Script
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        USER: ${{ secrets.USER }}
      run: |
        ssh $USER@$SERVER_IP << EOF
        cd lava-chess
        sudo git reset --hard
        sudo git pull origin main
        sudo mv config-prod.sj config.js
        sudo browserify client.js -o public/main.js
        sudo pm2 restart 0
        EOF
